// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("macwifibeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WF1v2zYXvs+vOOjV+wKysCZrMPhiWJYEq7GmDdbk2j0mjyUuEqmSVBzv1w+kqK9Ilp3auwnMr+d5Dnm+lBk80XYOObKNWIsVoT0DsMJm9HqSk2FaFFYoOT8DWAvKuHG/AGYgMac5MFVKS9rPAdhtQXPIlEzChKbvpdDE52B1SWGyCwu/hkmA+0+3V19v4fH+5urhFm6+XD/e3X5+uHpYfPl8dhZE99X+PpQZ8K6VtCikAabyXEl/LugHfEaR4SojEBIwy4CeSVqv3cQdM3t2OoDY/Zy24SElfwDUGmxKXiEYklzIxE9kKoGcjMGETAyLzi5/TJgGypB1At06U3ItklKjo4O1yChy824RLTxjVrqTUBriHlNYN5TKdsH8EUiVsYEp7H9QnqqnI3JrfuqbG35rcJS3eLeueHhpNeP+i2u0oQFNttSSOKy2nkoV5GhkAmZrLOWgJGxSwdJWeOfudCmlkMmIGity+kfJA9TUO/9LNc+kjVByv5iwsXYr787+8ROSTgpxsKkwlSvHfdd995szxVjMi3e9OOVoaSpO10rnaHv76AXzwoXeVZmUxsL5pU3h/Kf3lxG8P59ffJh/uIgvLs4Pu10vCTaVI1MIQxcgmpjSHDZoWvteGWUxMdMsV3olrEa99Xur22LoUoH394J09VAouR9YjdIgs+17VPf0irjKDr17VKu/idWxVg2W1coTbTdK82mhTa4qDek2plyCqsheKSCtVT/hJlqVxTTJrTtUZ0BWMTr/Rc6F24sZCLlWLrIZGp+/PI+Ja2foJP+umpDMmvlak6UX25ncIauVFnDiAQFTfIjeKTEHoTuQIbTDGkD33+wg9MpNQolimSp5W6Ou3RAKrZ4FJ2emRY4Wx8vWXViFtVZ5hdQcNe6t2hSEnC/9hmUN6XYyMkbpnVXMbY39qbiGfR3YxPZE7+dOeesrjOFeGSOc4/qaZAA1OcAIEkYRKA1cJMJiphihjHdqE9JYlIyWYk/oLMJGWNzUklwRcW1MKuTr0B1j2F+ZGo5uXT+MJWxYdvysuWd7HufERZlPs99VEN7F3kYe2hyRCbtddkpeo6A0M0JjZ+/ZnkTaAQJfEUVb7YSp5AjTlrkJl/O5sXnVRkpYmb0c7nrhiNPyh1JJRlWk7WbXlOwttX/5PfvsC4HOFXvy8RMi/aYej4BXa2AsWpd+s4yYq9k+zKs1F7MmVdouqwowhzVmxj0aSpYqXfPNmijf0ZE3smC0PuzK46EmkI4FPy4nPkrxvaQWEAQfy+oNXT5WPt7E2PULD1d3p0GAayRWpcgsKDklpZMMflDJdcPpsKa4MlxRZgZsvV4CpvuJPVoW/iYqnsZpnTO3LvuxGo2ALFwz0HFUV+UGqaf1TTe/1zMD99v88vg3+Rg+K4avcSJPrxLEiJOjZqmwxGypT2BDDw7+R3ESw8svl8vLnyNAnUdQFCyCXBTm/0MpysRFhta19Mcp+fIVaqCggZG0ykRQrkppywg2QnK12SGi/8Xz4xoCzijHGnORbY+mqGCCkZp4ijYCTiuBMoK1JloZPmWtKAYSelMT7J+EsS6hLe5nyLkmY8gMCXJkxxlZ06So+QY1tWQRlKbELNvC3dV1V0OdR57KFWlJlkybTf7szo3QtutNG9zvaVtQ6OaS6bLYHtqbgHqi4U1pqFD8BOWhcwOF4lVuG6Uqj01NHaZ7xeFxcTMkcn9Ngex0RrWIQzL3BXbSG3SIO67w0OJ6GFGFBjkWQyaUUln//6+T0XUgxzlP2bB0eFmvd5miPUHLNspb4f4bAAD//2MnnSQ="
}
